pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
               git url: 'https://github.com/dperezcabrera/dockerfiles.git'
            }
        }
        stage('Build') {
            steps {
               sh 'cd ic/jenkins; docker build -t dperezcabrera/jenkins-alpine:latest .'
            }
        }
    }
}
