pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
               git url: 'https://github.com/dperezcabrera/dockerfiles.git'
            }
        }
        stage('Build') {
            steps {
                sh '''
                    cd ic/jenkinsfile-runner;
                    docker build -t dperezcabrera/jenkinsfile-runner-alpine:latest .
                '''
            }
        }
    }
}

